# Generated by Django 5.2.5 on 2025-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
    ]
